import { Inter } from "next/font/google";
import "./globals.scss";
import { LoggedContextProvider } from "./context/loginContext";
import { DarkContextProvider } from "./context/darkContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "bookgram",
  description: "Generated by @felip.codes",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br">
      <head>
        <link rel="shortcut icon" href="./favicom.ico" type="image/x-icon" />
      </head>
      <body className={inter.className}>
        <LoggedContextProvider>
          <DarkContextProvider>{children}</DarkContextProvider>
        </LoggedContextProvider>
      </body>
    </html>
    
  );
}
