import { Inter,Roboto } from "next/font/google";
//import { Roboto } from 'next/font/google'
import "./globals.scss";
import { LoggedContextProvider } from "./context/loginContext";
import { DarkContextProvider } from "./context/darkContext";
import { StorageContextProvider } from "./context/storageContext";

const inter = Inter({ subsets: ["latin"] });
const roboto = Roboto({
  weight: "400",
  subsets: ['latin'],
})

export const metadata = {
  title: "bookgram",
  description: "Generated by @felip.codes",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br">
      <head>
        <link rel="shortcut icon" href="./favicom.ico" type="image/x-icon" />
      </head>
      <body className={roboto.className}>
        <StorageContextProvider>
          <LoggedContextProvider>
          <DarkContextProvider>{children}</DarkContextProvider>
        </LoggedContextProvider>
        </StorageContextProvider>
        
      </body>
    </html>
    
  );
}
